name: trajan_market
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  contained_tab_bar_view: 0.8.0
  http: 0.13.4
  cached_network_image: 3.2.1
  google_fonts: 2.3.2
  shimmer: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
   - assets/
  uses-material-design: true

