name: trajan_market
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  contained_tab_bar_view: 0.8.0
  http: 0.13.4
  cached_network_image: 3.2.1
  google_fonts: 2.3.2
  shimmer: 2.0.0
  get_storage: 2.0.3
  badges: 2.0.2
  persistent_bottom_nav_bar_v2: 4.2.3
  carousel_slider: 4.1.1
  intl: 0.17.0
  cloud_firestore: 3.1.17
  firebase_core: 1.17.1
  firebase_auth: 3.3.19
  introduction_screen: 3.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

